<?php

return [
    'multiple_choice' => [
        'name' => 'Which LoL Champion Are You?',
        'seed_survey_title' => 'Which LoL Champion Are You? [Conflict Matrix]',
        'entry' => 'Q1',
        'base_graph' => [
            'nodes' => [
                ['stable_key' => 'Q1', 'type' => 'multiple_choice', 'is_entry' => true, 'options' => ['A', 'B', 'C', 'D']],
                ['stable_key' => 'Q2', 'type' => 'multiple_choice', 'options' => ['A', 'B']],
                ['stable_key' => 'Q3', 'type' => 'multiple_choice', 'options' => ['A', 'B']],
                ['stable_key' => 'Q4', 'type' => 'multiple_choice', 'options' => ['A', 'B']],
                ['stable_key' => 'Q5', 'type' => 'multiple_choice', 'options' => ['A', 'B']],
                ['stable_key' => 'Q6', 'type' => 'multiple_choice', 'options' => ['A', 'B']],
                ['stable_key' => 'Q7', 'type' => 'multiple_choice', 'options' => ['A', 'B']],
                ['stable_key' => 'Q8', 'type' => 'multiple_choice', 'options' => ['A', 'B']],
                ['stable_key' => 'R_GAREN', 'type' => 'result'],
                ['stable_key' => 'R_LUX', 'type' => 'result'],
                ['stable_key' => 'R_YASUO', 'type' => 'result'],
                ['stable_key' => 'R_THRESH', 'type' => 'result'],
                ['stable_key' => 'R_TEEMO', 'type' => 'result'],
                ['stable_key' => 'R_JINX', 'type' => 'result'],
                ['stable_key' => 'R_BRAUM', 'type' => 'result'],
                ['stable_key' => 'R_SORAKA', 'type' => 'result'],
                ['stable_key' => 'R_AHRI', 'type' => 'result'],
                ['stable_key' => 'R_NASUS', 'type' => 'result'],
                ['stable_key' => 'R_EZREAL', 'type' => 'result'],
            ],
            'edges' => [
                ['from' => 'Q1', 'answer' => 'A', 'to' => 'Q2'],
                ['from' => 'Q1', 'answer' => 'B', 'to' => 'Q3'],
                ['from' => 'Q1', 'answer' => 'C', 'to' => 'Q4'],
                ['from' => 'Q1', 'answer' => 'D', 'to' => 'Q5'],
                ['from' => 'Q2', 'answer' => 'A', 'to' => 'Q6'],
                ['from' => 'Q2', 'answer' => 'B', 'to' => 'Q7'],
                ['from' => 'Q3', 'answer' => 'A', 'to' => 'R_TEEMO'],
                ['from' => 'Q3', 'answer' => 'B', 'to' => 'R_JINX'],
                ['from' => 'Q4', 'answer' => 'A', 'to' => 'Q8'],
                ['from' => 'Q4', 'answer' => 'B', 'to' => 'R_BRAUM'],
                ['from' => 'Q5', 'answer' => 'A', 'to' => 'R_NASUS'],
                ['from' => 'Q5', 'answer' => 'B', 'to' => 'R_EZREAL'],
                ['from' => 'Q6', 'answer' => 'A', 'to' => 'R_GAREN'],
                ['from' => 'Q6', 'answer' => 'B', 'to' => 'R_LUX'],
                ['from' => 'Q7', 'answer' => 'A', 'to' => 'R_YASUO'],
                ['from' => 'Q7', 'answer' => 'B', 'to' => 'R_THRESH'],
                ['from' => 'Q8', 'answer' => 'A', 'to' => 'R_SORAKA'],
                ['from' => 'Q8', 'answer' => 'B', 'to' => 'R_AHRI'],
            ],
            'canonical_paths' => [
                'P01_GAREN' => ['Q1:A', 'Q2:A', 'Q6:A', 'R_GAREN'],
                'P02_LUX' => ['Q1:A', 'Q2:A', 'Q6:B', 'R_LUX'],
                'P03_YASUO' => ['Q1:A', 'Q2:B', 'Q7:A', 'R_YASUO'],
                'P04_THRESH' => ['Q1:A', 'Q2:B', 'Q7:B', 'R_THRESH'],
                'P05_TEEMO' => ['Q1:B', 'Q3:A', 'R_TEEMO'],
                'P06_JINX' => ['Q1:B', 'Q3:B', 'R_JINX'],
                'P07_BRAUM' => ['Q1:C', 'Q4:B', 'R_BRAUM'],
                'P08_SORAKA' => ['Q1:C', 'Q4:A', 'Q8:A', 'R_SORAKA'],
                'P09_AHRI' => ['Q1:C', 'Q4:A', 'Q8:B', 'R_AHRI'],
                'P10_NASUS' => ['Q1:D', 'Q5:A', 'R_NASUS'],
                'P11_EZREAL' => ['Q1:D', 'Q5:B', 'R_EZREAL'],
            ],
        ],
        'common_checkpoint' => [
            'current_stable_key' => 'Q7',
            'answers' => [
                'Q1' => 'A',
                'Q2' => 'B',
            ],
        ],
        'scenarios' => [
            [
                'id' => 'MC_ATOMIC_01',
                'policy_class' => 'atomic_recovery',
                'title' => 'Unrelated edge deletion does not disturb active branch',
                'checkpoint' => 'common',
                'mutation' => [
                    ['op' => 'delete_edge', 'from' => 'Q1', 'answer' => 'B', 'to' => 'Q3'],
                ],
                'expected' => [
                    'recovery_strategy' => 'atomic_recovery',
                    'conflict_detected' => false,
                    'continue_from' => 'Q7',
                    'drop_answers' => [],
                    'must_not_show_unreachable' => [],
                ],
            ],
            [
                'id' => 'MC_ATOMIC_02',
                'policy_class' => 'atomic_recovery',
                'title' => 'Unrelated node deletion does not disturb active branch',
                'checkpoint' => 'common',
                'mutation' => [
                    ['op' => 'delete_node', 'stable_key' => 'Q3'],
                ],
                'expected' => [
                    'recovery_strategy' => 'atomic_recovery',
                    'conflict_detected' => false,
                    'continue_from' => 'Q7',
                    'drop_answers' => [],
                    'must_not_show_unreachable' => [],
                ],
            ],
            [
                'id' => 'MC_RB_01',
                'policy_class' => 'rollback_to_fallback',
                'title' => 'Bypass deleted intermediate node by rerouting entry answer directly to current node',
                'checkpoint' => 'common',
                'mutation' => [
                    ['op' => 'delete_edge', 'from' => 'Q1', 'answer' => 'A', 'to' => 'Q2'],
                    ['op' => 'add_edge', 'from' => 'Q1', 'answer' => 'A', 'to' => 'Q7'],
                ],
                'expected' => [
                    'recovery_strategy' => 'rollback',
                    'conflict_detected' => true,
                    'continue_from' => 'Q7',
                    'drop_answers' => ['Q2'],
                    'must_not_show_unreachable' => ['Q2'],
                    'note' => 'Behavior still lands user on Q7, but stored Q2 answer is discarded because Q2 is no longer on replay path.',
                ],
            ],
            [
                'id' => 'MC_ATOMIC_03',
                'policy_class' => 'atomic_recovery',
                'title' => 'Adding extra option/edge without invalidating replayed path keeps session atomic',
                'checkpoint' => 'common',
                'mutation' => [
                    ['op' => 'add_option', 'question' => 'Q2', 'value' => 'C', 'label' => 'C'],
                    ['op' => 'add_edge', 'from' => 'Q2', 'answer' => 'C', 'to' => 'Q8'],
                ],
                'expected' => [
                    'recovery_strategy' => 'atomic_recovery',
                    'conflict_detected' => false,
                    'continue_from' => 'Q7',
                    'drop_answers' => [],
                    'must_not_show_unreachable' => [],
                ],
            ],
            [
                'id' => 'MC_RB_02',
                'policy_class' => 'rollback_to_fallback',
                'title' => 'Deleting Q2 and removing Q1:A branch rolls back to entry',
                'checkpoint' => 'common',
                'mutation' => [
                    ['op' => 'delete_edge', 'from' => 'Q1', 'answer' => 'A', 'to' => 'Q2'],
                    ['op' => 'delete_node', 'stable_key' => 'Q2'],
                ],
                'expected' => [
                    'recovery_strategy' => 'rollback',
                    'conflict_detected' => true,
                    'continue_from' => 'Q1',
                    'drop_answers' => ['Q1', 'Q2'],
                    'must_not_show_unreachable' => ['Q7'],
                ],
            ],
            [
                'id' => 'MC_RB_03',
                'policy_class' => 'rollback_to_fallback',
                'title' => 'Deleting Q2:B branch keeps Q2 but requires fresh answer there',
                'checkpoint' => 'common',
                'mutation' => [
                    ['op' => 'delete_edge', 'from' => 'Q2', 'answer' => 'B', 'to' => 'Q7'],
                ],
                'expected' => [
                    'recovery_strategy' => 'rollback',
                    'conflict_detected' => true,
                    'continue_from' => 'Q2',
                    'drop_answers' => ['Q2'],
                    'must_not_show_unreachable' => ['Q7'],
                ],
            ],
            [
                'id' => 'MC_RB_04',
                'policy_class' => 'rollback_to_fallback',
                'title' => 'Changing Q2:B destination reroutes fallback to new target',
                'checkpoint' => 'common',
                'mutation' => [
                    ['op' => 'delete_edge', 'from' => 'Q2', 'answer' => 'B', 'to' => 'Q7'],
                    ['op' => 'add_edge', 'from' => 'Q2', 'answer' => 'B', 'to' => 'Q8'],
                ],
                'expected' => [
                    'recovery_strategy' => 'rollback',
                    'conflict_detected' => true,
                    'continue_from' => 'Q8',
                    'drop_answers' => [],
                    'must_not_show_unreachable' => ['Q7'],
                    'note' => 'Q2 answer remains valid and now resolves to Q8 in the new DAG.',
                ],
            ],
            [
                'id' => 'MC_NUCLEAR_01',
                'policy_class' => 'nuclear_restart',
                'title' => 'Deleting entry node forces restart from new entry with no kept answers',
                'checkpoint' => 'common',
                'mutation' => [
                    ['op' => 'delete_node', 'stable_key' => 'Q1'],
                    ['op' => 'set_entry', 'stable_key' => 'Q4'],
                ],
                'expected' => [
                    'recovery_strategy' => 'rollback',
                    'conflict_detected' => true,
                    'continue_from' => 'Q4',
                    'drop_answers' => ['Q1', 'Q2'],
                    'must_not_show_unreachable' => ['Q7'],
                    'note' => 'Implementation reports rollback strategy, but this is policy-level nuclear restart (restart_from_entry).',
                ],
            ],
            [
                'id' => 'MC_ATOMIC_04',
                'policy_class' => 'text_label_only_edit',
                'title' => 'Question/option text edits keep path intact',
                'checkpoint' => 'common',
                'mutation' => [
                    ['op' => 'update_question_title', 'stable_key' => 'Q1', 'title' => 'Choose your playstyle'],
                    ['op' => 'update_option_label', 'question' => 'Q2', 'value' => 'B', 'label' => 'Strategic'],
                ],
                'expected' => [
                    'recovery_strategy' => 'atomic_recovery',
                    'conflict_detected' => false,
                    'continue_from' => 'Q7',
                    'drop_answers' => [],
                    'must_not_show_unreachable' => [],
                ],
            ],
        ],
    ],
    'rating' => [
        'name' => 'LoL Champion Persona (Rating)',
        'seed_survey_title' => 'LoL Champion Persona (Rating) [Conflict Matrix]',
        'entry' => 'q1',
        'base_graph' => [
            'nodes' => [
                ['stable_key' => 'q1', 'type' => 'rating', 'is_entry' => true, 'title' => 'How aggressive is your playstyle?'],
                ['stable_key' => 'q2', 'type' => 'rating', 'title' => 'How team-oriented are you?'],
                ['stable_key' => 'q3', 'type' => 'rating', 'title' => 'How much do you prefer scaling?'],
                ['stable_key' => 'q4', 'type' => 'rating', 'title' => 'How confident are you in mechanics?'],
            ],
            'edges' => [],
            'canonical_paths' => [
                'L01' => ['q1', 'q2', 'q3', 'q4'],
            ],
        ],
        'checkpoints' => [
            'at_q2' => [
                'current_stable_key' => 'q2',
                'answers' => [
                    'q1' => 4,
                ],
            ],
            'at_q3' => [
                'current_stable_key' => 'q3',
                'answers' => [
                    'q1' => 4,
                    'q2' => 3,
                ],
            ],
        ],
        'scenarios' => [
            [
                'id' => 'RT_ATOMIC_01',
                'policy_class' => 'atomic_recovery',
                'title' => 'Deleting future node q3 while user is at q2 keeps cursor at q2',
                'checkpoint' => 'at_q2',
                'mutation' => [
                    ['op' => 'delete_node', 'stable_key' => 'q3'],
                ],
                'expected' => [
                    'recovery_strategy' => 'atomic_recovery',
                    'conflict_detected' => false,
                    'continue_from' => 'q2',
                    'drop_answers' => [],
                    'must_not_show_unreachable' => [],
                ],
            ],
            [
                'id' => 'RT_RB_01',
                'policy_class' => 'rollback_to_fallback',
                'title' => 'Deleting answered q2 while current q3 survives replays to q3 and drops q2 answer',
                'checkpoint' => 'at_q3',
                'mutation' => [
                    ['op' => 'delete_node', 'stable_key' => 'q2'],
                    ['op' => 'set_order', 'ordered_stable_keys' => ['q1', 'q3', 'q4']],
                ],
                'expected' => [
                    'recovery_strategy' => 'rollback',
                    'conflict_detected' => true,
                    'continue_from' => 'q3',
                    'drop_answers' => ['q2'],
                    'must_not_show_unreachable' => [],
                ],
            ],
            [
                'id' => 'RT_RB_02',
                'policy_class' => 'rollback_to_fallback',
                'title' => 'Deleting q2 and moving q4 before q3 falls back to q4',
                'checkpoint' => 'at_q3',
                'mutation' => [
                    ['op' => 'delete_node', 'stable_key' => 'q2'],
                    ['op' => 'set_order', 'ordered_stable_keys' => ['q1', 'q4', 'q3']],
                ],
                'expected' => [
                    'recovery_strategy' => 'rollback',
                    'conflict_detected' => true,
                    'continue_from' => 'q4',
                    'drop_answers' => ['q2'],
                    'must_not_show_unreachable' => [],
                ],
            ],
            [
                'id' => 'RT_RB_03',
                'policy_class' => 'rollback_to_fallback',
                'title' => 'Reordering to q1-q4-q3-q2 falls back to q4 from q3 checkpoint',
                'checkpoint' => 'at_q3',
                'mutation' => [
                    ['op' => 'set_order', 'ordered_stable_keys' => ['q1', 'q4', 'q3', 'q2']],
                ],
                'expected' => [
                    'recovery_strategy' => 'rollback',
                    'conflict_detected' => true,
                    'continue_from' => 'q4',
                    'drop_answers' => ['q2'],
                    'must_not_show_unreachable' => [],
                ],
            ],
            [
                'id' => 'RT_NUCLEAR_01',
                'policy_class' => 'nuclear_restart',
                'title' => 'Deleting q1 and moving unanswered q4 to front restarts from q4 with no kept answers',
                'checkpoint' => 'at_q3',
                'mutation' => [
                    ['op' => 'delete_node', 'stable_key' => 'q1'],
                    ['op' => 'set_order', 'ordered_stable_keys' => ['q4', 'q2', 'q3']],
                ],
                'expected' => [
                    'recovery_strategy' => 'rollback',
                    'conflict_detected' => true,
                    'continue_from' => 'q4',
                    'drop_answers' => ['q1', 'q2'],
                    'must_not_show_unreachable' => [],
                    'note' => 'Implementation reports rollback strategy; policy-wise this is restart-from-entry behavior.',
                ],
            ],
        ],
    ],
    'open_ended' => [
        'name' => 'LoL Champion Persona (Open Ended)',
        'seed_survey_title' => 'LoL Champion Persona (Open Ended) [Conflict Matrix]',
        'entry' => 'q1',
        'base_graph' => [
            'nodes' => [
                ['stable_key' => 'q1', 'type' => 'text', 'is_entry' => true, 'title' => 'Describe your ideal lane.'],
                ['stable_key' => 'q2', 'type' => 'text', 'title' => 'Describe your risk appetite.'],
                ['stable_key' => 'q3', 'type' => 'text', 'title' => 'Describe your teamfight role.'],
                ['stable_key' => 'q4', 'type' => 'text', 'title' => 'Describe your win condition focus.'],
            ],
            'edges' => [],
            'canonical_paths' => [
                'L01' => ['q1', 'q2', 'q3', 'q4'],
            ],
        ],
        'checkpoints' => [
            'at_q2' => [
                'current_stable_key' => 'q2',
                'answers' => [
                    'q1' => 'I like controlling mid lane tempo.',
                ],
            ],
            'at_q3' => [
                'current_stable_key' => 'q3',
                'answers' => [
                    'q1' => 'I like controlling mid lane tempo.',
                    'q2' => 'I take calculated risks when vision is secured.',
                ],
            ],
        ],
        'scenarios' => [
            [
                'id' => 'OE_ATOMIC_01',
                'policy_class' => 'atomic_recovery',
                'title' => 'Deleting future node q3 while user is at q2 keeps cursor at q2',
                'checkpoint' => 'at_q2',
                'mutation' => [
                    ['op' => 'delete_node', 'stable_key' => 'q3'],
                ],
                'expected' => [
                    'recovery_strategy' => 'atomic_recovery',
                    'conflict_detected' => false,
                    'continue_from' => 'q2',
                    'drop_answers' => [],
                    'must_not_show_unreachable' => [],
                ],
            ],
            [
                'id' => 'OE_RB_01',
                'policy_class' => 'rollback_to_fallback',
                'title' => 'Deleting answered q2 while current q3 survives replays to q3 and drops q2 answer',
                'checkpoint' => 'at_q3',
                'mutation' => [
                    ['op' => 'delete_node', 'stable_key' => 'q2'],
                    ['op' => 'set_order', 'ordered_stable_keys' => ['q1', 'q3', 'q4']],
                ],
                'expected' => [
                    'recovery_strategy' => 'rollback',
                    'conflict_detected' => true,
                    'continue_from' => 'q3',
                    'drop_answers' => ['q2'],
                    'must_not_show_unreachable' => [],
                ],
            ],
            [
                'id' => 'OE_RB_02',
                'policy_class' => 'rollback_to_fallback',
                'title' => 'Deleting q2 and moving q4 before q3 falls back to q4',
                'checkpoint' => 'at_q3',
                'mutation' => [
                    ['op' => 'delete_node', 'stable_key' => 'q2'],
                    ['op' => 'set_order', 'ordered_stable_keys' => ['q1', 'q4', 'q3']],
                ],
                'expected' => [
                    'recovery_strategy' => 'rollback',
                    'conflict_detected' => true,
                    'continue_from' => 'q4',
                    'drop_answers' => ['q2'],
                    'must_not_show_unreachable' => [],
                ],
            ],
            [
                'id' => 'OE_RB_03',
                'policy_class' => 'rollback_to_fallback',
                'title' => 'Reordering to q1-q4-q3-q2 falls back to q4 from q3 checkpoint',
                'checkpoint' => 'at_q3',
                'mutation' => [
                    ['op' => 'set_order', 'ordered_stable_keys' => ['q1', 'q4', 'q3', 'q2']],
                ],
                'expected' => [
                    'recovery_strategy' => 'rollback',
                    'conflict_detected' => true,
                    'continue_from' => 'q4',
                    'drop_answers' => ['q2'],
                    'must_not_show_unreachable' => [],
                ],
            ],
            [
                'id' => 'OE_NUCLEAR_01',
                'policy_class' => 'nuclear_restart',
                'title' => 'Deleting q1 and moving unanswered q4 to front restarts from q4 with no kept answers',
                'checkpoint' => 'at_q3',
                'mutation' => [
                    ['op' => 'delete_node', 'stable_key' => 'q1'],
                    ['op' => 'set_order', 'ordered_stable_keys' => ['q4', 'q2', 'q3']],
                ],
                'expected' => [
                    'recovery_strategy' => 'rollback',
                    'conflict_detected' => true,
                    'continue_from' => 'q4',
                    'drop_answers' => ['q1', 'q2'],
                    'must_not_show_unreachable' => [],
                    'note' => 'Implementation reports rollback strategy; policy-wise this is restart-from-entry behavior.',
                ],
            ],
        ],
    ],
];
